application: ucscslugger
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /init.py
  script: init.py

- url: /joingame.py
  script: joingame.py

- url: /getgamestatus.py
  script: getgamestatus.py

- url: /postgamemove.py
  script: postgamemove.py

- url: /adduser.py
  script: adduser.py

- url: /updateuser.py
  script: updateuser.py

- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.2"
